### ISSUE TITLE
Plugin does not work if Eclipse is not running explicitly on Java 8

### ISSUE THREAD

**Issue by tuxtor** [payara/ecosystem-eclipse-glassfish-plugin#2]
Recently I did a new install of Eclipse Photon over MacOS. Since this machine has two JDKs installed (Java 8 and Java 10) Eclipse Photon detects Java 10 as the default runtime environment (ignoring $JAVA_HOME).

Although Payara could be installed and added to the IDE, console windows never shows up and if the server is stopped, Eclipse will raise an error similar to this:
 
> An internal error occurred during: "Stopping Payara Server 4 (4.1.2.1) [domain1]".
Can't find bundle for base name sun.util.logging.resources.logging, locale en_GT

I've also confirmed that plugin works if Java 8 is forced on eclipse by using -vm argument on Eclipse.ini

AFAIK Payara Itself only supports Java 8 but I didn't find any indications of this as requirement in Payara Tools (at least not in Eclipse Marketplace or Payara Blog), maybe this should be added as a warning.

For the record, I also reported this on Glassfish Tools https://marketplace.eclipse.org/comment/4948#comment-4948 some months ago.

**Comment by andi-huber** [comment]
I'm running into the same issue. 

```
java.util.MissingResourceException: Can't find bundle for base name sun.util.logging.resources.logging, locale en_US
	at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2045)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1679)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1583)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1546)
	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:914)
	at org.eclipse.payara.tools.log.LevelResolver.getLocalized(LevelResolver.java:58)
```

This little workaround in **LevelResolver** fixes it for me:
```
    private String getLocalized(String text, String logBundleName, Locale logLocale) {
        try {
            ResourceBundle bundle = ResourceBundle.getBundle(logBundleName, logLocale); // throws !!!
            String localized = bundle.getString(text);
            return localized;
        } catch (Exception e) {
            return text; // fallback
        }
    }
```

**Comment by arjantijms** [comment]
Thanks for the report. Indeed, the tools themselves are limited to Java 8 too. The current release is basically a pre-release, and still needs some work. Hope to find some time for this soon.

**Comment by arjantijms** [comment]
Fixed as per https://github.com/payara/ecosystem-eclipse-glassfish-plugin/commit/c5a139f2539ec2610b7bd02e9e13fade4f59fe95
