### ISSUE TITLE
Payara 5.184 error while starting with the eclipse plugin

### ISSUE THREAD

**Issue by ionutursuleanu** [payara/ecosystem-eclipse-glassfish-plugin#5]
Payara 5.184 doesn't work with the eclipse plugin. At startup, the following error appears:

`Error: Could not find or load main class [1.8.0|1.8.0u120]-Xbootclasspath.p:.Users.ionutursuleanu.Downloads.payara5.glassfish.lib.grizzly-npn-bootstrap-1.6.jar
`
## Environment ##

- **Eclipse Version**: 18.09
- **Payara Version**: 5.184
- **Edition**: Full
- **JDK Version**: 8 u192 - Oracle
- **Operating System**: Windows / Linux / Mac

**Comment by rmanitz** [comment]
same here

**Comment by njckami** [comment]
Same problem.
Eclipse 18.09
Payara Version 5.184
JDK Version: 8 u192 - Oracle
OS Linux Fedora 29

**Comment by lprimak** [comment]
This is fixed with the latest version of Eclipse plugin.

**Comment by rmanitz** [comment]
is it published to the eclipse marketplace ? 
where ist the current update site ?
