### ISSUE TITLE
Install error on eclipse 2018-12

### ISSUE THREAD

**Issue by ionutursuleanu** [payara/ecosystem-eclipse-glassfish-plugin#6]
Hi,

The following error appears on eclipse 2018-12 at install:

> Cannot complete the install because one or more required items could not be found.
  Software being installed: Payara Tools 1.0.0.201804032346 (org.eclipse.payara.tools.feature.group 1.0.0.201804032346)
  Missing requirement: Payara Tools 1.0.0.201804032346 (org.eclipse.payara.tools.feature.group 1.0.0.201804032346) requires 'org.eclipse.equinox.p2.iu; org.eclipse.sapphire.modeling.xml.feature.group [9.1.0,10.0.0)' but it could not be found

**Comment by ahamana** [comment]
Same error on eclipse 2019-3.

**Comment by arjantijms** [comment]
Fixed via internal issue EP-18, committed here: https://github.com/payara/ecosystem-eclipse-glassfish-plugin/commit/dc8a617a7b26e9861e5f0cd31bb9e993d265738f
