### ISSUE TITLE
Payara 5.191 - Jakarta EE libraries classpath not set

### ISSUE THREAD

**Issue by tkernstock** [payara/ecosystem-eclipse-glassfish-plugin#7]
Hi,
I tried to use the new 5.191 in my eclipse 2012-12 project. After changing to the new runtime my project doesn't compile anymore because all javax.faces dependencies are gone.

I looked into it and found, that the javax.faces.jar was replaced by jakarta.faces.jar which is not in the "Payara System libraries" classpath of the project anymore. 

Please fix.

Thanx Thomas

PS: The classpath problem seems to be recurring, since I had the same problem upgrading version 4s with the validation apis. Would be great if a more flexibel version for building the payara classpath could be found.

**Comment by tkernstock** [comment]
Could you please replace the code in PayaraLocationUtils at line 116 with this one:

` private static final String[] LIBRARIES_5 = {
            "glassfish/modules/javax.*.jar",
            "glassfish/modules/jakarta.*.jar",
            "glassfish/modules/weld-osgi-bundle.jar",
            "glassfish/modules/bean-validator.jar",
            "glassfish/modules/jersey-*.jar",
            "glassfish/modules/glassfish-api.jar",
            "glassfish/modules/ha-api.jar",
            "glassfish/modules/endorsed/*.jar",
            "glassfish/modules/org.eclipse.persistence*.jar",
            "glassfish/modules/jaxb*.jar",
            "glassfish/modules/webservices*.jar",
            "glassfish/modules/cdi-api.jar", // +
            "mq/lib/jaxm-api.jar"
};`

**Comment by jGauravGupta** [comment]
Internal issue EP-26 to address it.

**Comment by arjantijms** [comment]
>Would be great if a more flexibel version for building the payara classpath could be found.

Yes, this is somewhat of a general issue with many Eclipse plug-ins, not just the Payara one. It's part of the reason why plug-ins support a certain version of a server and either refuse to work with- or display a warning about, a newer server version.

More advanced classpath and source-code lookup is being considered for a future version though.

**Comment by arjantijms** [comment]
See commit https://github.com/payara/ecosystem-eclipse-glassfish-plugin/commit/6921de380e11d81f5416e46940f9a351c8739c9f

And PR https://github.com/payara/ecosystem-eclipse-glassfish-plugin/pull/8

This implements a new set of libraries for 5.191+ and a very basic selector for "all" libraries as ultimate fallback. The mentioned source-code lookup is still considered for a future version.

**Comment by tkernstock** [comment]
Hi Arjan,
thank you implementing this!
